### PR TITLE
Install correct bundler version for dev

### PR DESCRIPTION
**Pull request by xfalcox**

### CODE REVIEW

**Comment by gschlager** [comment]
Isn't bundler supposed to install the correct version of bundler automatically? I've seen it install the version from `Gemfile.lock` multiple times recently when a different version of bundler was running. :thinking:

**Comment by davidtaylorhq** [comment]
Yeah, modern version of bundler will auto-install the version from the lockfile. I wonder if the permissions errors we're seeing are because our original install of bundler is done as root, and then in the dev image we switch to the `discourse` user?

**Comment by xfalcox** [comment]
Yes, that is exactly the case which is why I'm pre-installing the correct version of bundler in a step before as root.

**Comment by davidtaylorhq** [comment]
But then if someone's using the dev image, and they pull the latest discourse core without updating the image, they would run into the same issue?

**Comment by davidtaylorhq** [comment]
This should do it: https://github.com/discourse/discourse_docker/pull/662

**Pull request closed without merging**
