### PR TITLE
Bump acme.sh to 2.8.0

### PR DESCRIPTION
**Pull request by sau226**
Bump the acme.sh script (Let's Encrypt) version for more API options, ACME v2 wildcard certs and bug fixes

### CODE REVIEW

**Comment by SamSaffron** [comment]
@tgxworld  what are your thoughts here? 

@sau226 what are the advantages of the upgrade?

**Comment by tgxworld** [comment]
Acme.sh actually has automatic upgrade built in if I recall correctly so this probably won’t make a difference more most instances.

**Comment by sau226** [comment]
Actually it looks like we (Discourse) manually force a specific commit hash so this commit updates the hash. I can modify the PR to just use the latest version provided if you want.

**Comment by tgxworld** [comment]
@sau226 This looks OK. Thank you for contribution :+1:

**Pull request merged**
