### PR TITLE
Handle the case where IPv6 is also used

### PR DESCRIPTION
**Pull request by Supermathie**
* We want web.ssl.template.yml to handle the IPv6 case as well

### CODE REVIEW

**Comment by Supermathie** [comment]
Don't merge this yet, I'm still testing it, but this makes certain workflows a bit nicer

**Comment by jomaxro** [comment]
You can make it a draft if not yet safe to merge.

**Comment by Supermathie** [comment]
another thing I'd like to consider is that this `sed` feels brittle - should we change the discourse_docker base image to:
* have a marker for replacement
* listen on both v4 and v6 by default

**Review by SamSaffron — APPROVED** [review]

**Comment by SamSaffron** [comment]
I think this is fine, but why did you remove the hook?

**Comment by Supermathie** [comment]
I *moved* the hook.

**Pull request merged**
