### PR TITLE
PostgreSQL 12

### PR DESCRIPTION
**Pull request by xfalcox**

### CODE REVIEW

**Comment by SamSaffron** [comment]
I think this is good, feel free to merge once you carefully test it. 

Be sure to deploy a few sites ... maybe Jeff's blog and others to confirm all went well

**Comment by empeje** [comment]
Hi @SamSaffron and @xfalcox I tried it on my Digital Ocean droplets, and it breaks my discourse installation.

**Comment by xfalcox** [comment]
Yes @empeje  it needs a follow up new image that is being built right now. Follow https://meta.discourse.org/t/clean-install-fails-because-of-pg12/151212/6?u=falco for updates

**Comment by empeje** [comment]
Thanks for the clarification @xfalcox, I'm new to discord, and just installed it when you put update for PSQL 12.

For someone who need immediate fix, my approach is I fork the repository and I revert the commit and I use that as the remote repo for my installation directory and I plan to go back to this official one once it stable.

**Comment by xfalcox** [comment]
It is already fixed in the main repo @empeje, please try again.

**Comment by empeje** [comment]
Thanks @xfalcox, appreciate it 🎉

**Pull request merged**
