### PR TITLE
Added cleanup command by Supermathie

### PR DESCRIPTION
**Pull request by LuaTenshi**
Added a the cleanup command to the launcher as suggested by Sam on https://meta.discourse.org/t/adding-an-easy-discourse-command/25841/2

The original code was written by Supermathie on https://meta.discourse.org/t/low-on-disk-space-cleaning-up-old-docker-containers/15792/18

### CODE REVIEW

**Comment by LuaTenshi** [comment]
Making this was very /awk/ward but I managed. Bash really need a "to human format" function so that writing out all of those things can be avoided. I know that some commands have it built in but imagine how nice it would be if echo had that option.

**Comment by LuaTenshi** [comment]
Think this is ready to get merged?

**Comment by SamSaffron** [comment]
sure, this looks good to me, Thanks!

**Comment by SamSaffron** [comment]
Something is odd / not working right

```
The following command will
- Delete all docker images for old containers
- Delete all stopped and orphan containers

Are you sure (Y/n): 

Starting Cleanup
Deleted: ec9d9b8fe19ff96a55a2bb11b43f92f2aff7d6e553336dc7a8d1432b78cf27cb
Deleted: 1c3840035127038d8465bbd72aed0ee9c912be110cf38e2cf040eb7d9c88cea1
Deleted: e93a3aa29787ddb3f3e924664c33cad6f059908bb2df64afd6dda0fbfad5d9fc
Deleted: 1b84b2c9f35090fcdefae59357c49b6938a95ac6d9ba2983923d99f8a3982fc6
Deleted: bb0d3dd02de9445b26f38d8eb50a9335bd9f51e541c18724cf1f98225ed92daa
Deleted: 057fd7f967d32ba612f1aab0a5de440e19fa75dc2bfb834a39d3d65040010fd2
Deleted: fd14ec38d7219d67520f71c903008717991e68a9681342cbd90844eb3982c292
Deleted: 0bf1d1c677857494ec359cdb6494a602673e99966f99faad16cb1e9b3a79250a
Deleted: 6798273decd9573ed85ef671ddfcfa7acefef83be7ce6336f2199a50ac867e01
Deleted: 10f9070b7912bcd88bfea756901f02747e72815b5f1eba86caa0ffa7e1dcd544
Deleted: 86b431e901f948bdd5f35695dfd5516beff698452cfd28677daf4e11cebd1f7e
Deleted: d315a5da075c2fd7dd74cc56618512f160a95de3e56837db824b183cbf29d4dd
Deleted: c0457faa0f34d96b65028168b8198e44874cb6ea0b60ae2bdac53dbfa75b3e67
Deleted: 8b0a8a7a0792de7ea67fd21b96dc0ee4820e7246370131bc348caf595f9beada
Deleted: be69dc1ca7b45aaa3fe19cf03c44f7b3d8d8fb70ae8ee9458882da9a5685b6f0
Deleted: 281cd4c9048fb910056fe9dd1225172182c427be45ce0a2f2e3803d5afa5766a
Deleted: 36fa609ba0caeb0840de24a4c683a8a509318b21d43298a0ee6743da9f426f81
Deleted: e76e24a958a36bdb0ddbdb0a8996871aa9da92ec4a98d504b8c7f06cdc4ddfb0
Deleted: 4347db5b322894533e756d184c16edeca54907016c66bb37e4f87af813ccfe5b
Deleted: 93eacca9f004a8239554e71e0c7c5b519744466a6b68dd034c445d6e09ca9ddc
./launcher cleanup has finished, no files were removed.

```

**Comment by LuaTenshi** [comment]
Alright, I will check it out in a bit.

**Pull request merged**
