### PR TITLE
Discourse setup reconfig

### PR DESCRIPTION
**Pull request by pfaffman**
This PR allows people to re-run `./discourse-setup`. This is useful to:

- Turn on Let's Encrypt after initial testing (and DNS config) **tested**
- Turn off Let's Encrypt (but why?) **tested** (see note below)
- adjust `db_shared_buffers` and `UNICORN_WORKERS if droplet is resized  **tested**
- Change Email config **tested**
- Works with my install script unchanged

### Notes

- For some reason, this PR shows changes having to do with MacOS memory checking. I didn't do that and don't understand why it's showing up here; when I look at the current version that stuff is there. Apparently I still don't understand git.
- If Let's Encrypt is disabled, the templates are commented out, but `LETSENCRYPT_ACCOUNT_EMAIL` is left configured. This means that if the script is subsequently re-run, it'll default to re-enabling Let's Encrypt. I suppose I could change this, but it seems like an edge case.
- Defaults now come from `standalone.yml` rather than this script. Future changes to `standalone.yml` could break this script (but that's always been the case).
- I added a second email to `DISCOURSE_DEVELOPER_EMAILS`; before you had to look at the comments to see how to include two addresses (and the default in this script included two addresses).
- If there is a space between email addresses in `DISCOURSE_DEVELOPER_EMAILS` they are read incorrectly by `read_config()`. It's inconvenient, but a real live human will be seeing what's there, so this seems acceptable.
- I changed the first line to `#!/usr/bin/env bash`, which should let this script run on macs. Not sure why whoever wrote the mac memory code didn't do this.
- I changed the final `./launcher bootstrap $app_name` to `time ./launcher rebuild $app_name`. Rebuild works fine when there's no image to delete. I like seeing how long things take. I'll take out the `time` if it's deemed annoying.
- I added a `sleep 5` between when changes are made and when the rebuild starts to give people a chance to ^c before it starts. Seems minimally annoying, and it can be impossible to kill `bundle` with a ^C. I'll remove this if it's deemed troublesome.
- Old script refused to run if port 80 or 443 was occupied. Now there is also a message to `./launcher stop app` and then re-run.
- When I ran this on forum.literatecomputing.com I noticed that it fixed memory settings that I'd apparently not set correctly when I set it up by hand.
- None of the error checking code (`validate_config`) was changed, so it should be pretty safe.
- I think that I checked all the cases if a given variable is commented out (as most are in `standalone.yml`) or not (as when re-running the script).

### CODE REVIEW

**Comment by xfalcox** [comment]
I didn't read the whole PR, but there's some white space changes too in `standalone.yml` that shouldn't be targeted at this PR, can you clean it please.

**Comment by pfaffman** [comment]
I thought that my emacs settings were such that the Right Thing was happening and that, though whitespace-only commits were frowned upon, fixing them up on a commit was OK.

From https://meta.discourse.org/t/discourse-development-contribution-guidelines/3823

    no trailing whitespaces, blank lines should have no spaces

And

[quote]
Remember: We don't accept pull requests consisting entirely of style changes. Style changes in the context of pull requests that also refactor code, fix bugs, improve functionality are welcome.
[/quote]

It appears that when I saved, emacs removed spurious spaces on blank lines, which I thought was the desired behavior.

Do I understand correctly that you want me to go back and insert spaces on the five blank lines that erroneously had spaces on them before?

**Comment by coding-horror** [comment]
Why are we adding OS X support? Why is that in scope? I don't think it is, and it complicates this PR.

**Comment by coding-horror** [comment]
also why read the defaults from the standalone.yml? I'm more comfortable with them being hard coded here in this script.

**Comment by ZogStriP** [comment]
This PR is too getting too big. @pfaffman, can you split it and do 1 PR per "changes"?

**Comment by pfaffman** [comment]
## WTF, OS X?

Or, WTF, github?

The OS X support is in the current version. I don't understand how or why it looks like I submitted it. Could it be that I didn't pull down the current version before I branched? I guess I can try to start a new PR to solve this. I'm fairly flummoxed on this. Here's that OSX stuff in the current release.

Have a look:

https://github.com/discourse/discourse_docker/blob/master/discourse-setup#L56-L62

Presumably I can ditch this PR and make a new one that doesn't seem to blame me for code that's already there. I was as surprised as you to find this OS X stuff here, and it can't even work with the current `#!/bin/bash`.

## Why move defaults into standalone.yml?

My proposed script always reads app.yml to get its initial values, so there is only one way that it gets default values. That seems clean. If defaults for the first run of  `discourse-setup` live in `discourse-setup` and on subsequent runs, it loads them from `app.yml` then there are two code bases to maintain, one for initial runs of the script and another for re-runs of the script. If you prefer, I can have a branch that does one thing if app.yml already exists and another if it doesn't, but I think it'll be more complicated and more code. My proposed implementation also potentially lets `discourse-setup` work with other sample.yml files in the future.

**Comment by coding-horror** [comment]
I see, fine on reading the file then but negatory on the OS X please

**Comment by pfaffman** [comment]
Here's the thing on the OSX nonsense. I didn't do it. It is already in the current version. See?

https://github.com/discourse/discourse_docker/blob/master/discourse-setup#L56-L62

Here's a blame link. It was added 4 months ago.

https://github.com/discourse/discourse_docker/blame/master/discourse-setup#L37-L42

If you like, I can abandon this PR, do a fresh pull, create a new branch, and see i f that will make Github not show those changes in the PR. I don't know how it is that I am so inept at dealing with Git.

**Pull request closed without merging**
