### PR TITLE
Create web.letsencrypt.cloudflare.ssl.template.yml

### PR DESCRIPTION
**Pull request by austinhquinn**
add these env vars and their values to your app.yml.

LETSENCRYPT_ACCOUNT_EMAIL
CLOUDFLARE_ACCOUNT_EMAIL
CLOUDFLARE_KEY

include this template, and then you can auth letsencrypt via cloudflare dns. (useful for subfolder installs)

### CODE REVIEW

**Comment by SamSaffron** [comment]
I follow but I worry about having yet another template to maintain long term. Maybe just post on meta for now?

**Comment by austinhquinn** [comment]
> I follow but I worry about having yet another template to maintain long term. Maybe just post on meta for now?

no problem. what's meta?

**Comment by SamSaffron** [comment]
@austinhquinn meta.discourse.org :) a topic there would be great! then people looking to setup with letsencrypt / cloudflare can follow the instructions.

**Comment by austinhquinn** [comment]
> @austinhquinn meta.discourse.org :) a topic there would be great! then people looking to setup with letsencrypt / cloudflare can follow the instructions.

oooo duh. sorry i havent worked on discourse since i posted that pull request.

**Pull request closed without merging**
