### PR TITLE
add the :Z option to all mounted volumes so that discourse works when selinux is enabled

### LINKED ISSUE #365: launcher needs a small tweak before it works on a machine that has selinux enabled (Fedora, RHEL, etc)
The bind mounts just need the :Z option on them.

### PR DESCRIPTION
**Pull request by db48x**
fixes #365

### CODE REVIEW

**Comment by SamSaffron** [comment]
This looks reasonable, let's try it out!

**Comment by SamSaffron** [comment]
Had to revert per: https://meta.discourse.org/t/update-to-1-9-0-beta5-fails-to-start-discourse-after-rebuild/67922/2

**Comment by db48x** [comment]
hilariously, I just tripped over it myself. easy to fix, see the commit I just pushed.

**Comment by SamSaffron** [comment]
yeah you we are going to need a new PR

**Pull request merged**
