### PR TITLE
let discourse-setup  install-docker

### PR DESCRIPTION
**Pull request by pfaffman**
Ubuntu 16.04 includes git, so novice users can run git and have `discourse-setup` install docker while it's setting up swap and so on, removing a step from the 30 minute install instructions.

In other news, Emacs, the One True Editor, removed a bunch of spurious white space. It's a little annoying.

### CODE REVIEW

**Comment by coding-horror** [comment]
oops this has conflicts now that I've merged the other PR. Can you rebase?

**Comment by xfalcox** [comment]
Ping @pfaffman 

Maybe open another PR with just the feature?

**Comment by pfaffman** [comment]
Oh. Sorry folks. This fell off my map. I'll see what I can do.

**Comment by pfaffman** [comment]
Oh. I submitted this in some other PR that was already merged.

**Pull request closed without merging**
